export const file = {
    id: "F07NYP4NZHV",
    created: 1727445070,
    timestamp: 1727445070,
    name: "Hello",
    title: "Hello",
    mimetype: "application/vnd.slack-docs",
    filetype: "quip",
    pretty_type: "Canevas",
    user: "USLACKBOT",
    user_team: "T07P77VJJ9J",
    editable: true,
    size: 91,
    mode: "quip",
    is_external: false,
    external_type: "",
    is_public: true,
    public_url_shared: false,
    display_as_bot: false,
    username: "",
    url_private: "https://files.slack.com/files-pri/T07P77VJJ9J-F07NYP4NZHV/canvas",
    url_private_download: "https://files.slack.com/files-pri/T07P77VJJ9J-F07NYP4NZHV/download/canvas",
    permalink: "https://slack-hre9480.slack.com/canvas/C07P6LY9Q8N",
    permalink_public: "https://slack-files.com/T07P77VJJ9J-F07NYP4NZHV-374a7571fd",
    url_static_preview: "https://slack-hre9480.slack.com/canvas/C07P6LY9Q8N/mobile",
    quip_thread_id: "fQS9AAAI3Ra",
    updated: 1728486500,
    update_notification: 1728486500,
    is_channel_space: true,
    linked_channel_id: "C07P6LY9Q8N",
    favorites: [],
    is_starred: false,
    shares: {},
    channels: [],
    groups: [],
    ims: [],
    has_more_shares: false,
    access: "write",
    private_channels_with_file_access_count: 0,
    private_file_with_access_count: 0,
    dm_mpdm_users_with_file_access: [
        {
            user_id: "USLACKBOT",
            access: "write",
        },
    ],
    teams_shared_with: [],
    has_rich_preview: false,
    file_access: "visible",
    org_or_workspace_access: "none",
    title_blocks: [
        {
            type: "rich_text",
            block_id: "/U8MW",
            elements: [
                {
                    type: "rich_text_section",
                    elements: [
                        {
                            type: "text",
                            text: "Hello ",
                        },
                    ],
                },
            ],
        },
    ],
    team_pref_version_history_enabled: true,
    can_toggle_canvas_lock: true,
    editors: ["U07PHD7UNUR", "U07Q2AA8JPK"],
    edit_timestamp: 1728486500,
    last_read: 1728486468257,
    show_badge: false,
    comments_count: 0,
};
