import { QueryProvider } from "@/providers/query-provider";
import { SocketProvider } from "@/providers/socket-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/providers/redux-provider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Slate",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                {/* Other head elements, if needed */}
                <link rel="icon" href="/assets/slack_logo.svg" />
            </head>
            <SocketProvider>
                <QueryProvider>
                    <Providers>
                        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
                    </Providers>
                </QueryProvider>
            </SocketProvider>
        </html>
    );
}
